### ISSUE TITLE
Differences of function node_potentials and feature_potentials

### ISSUE THREAD

**Issue by dominjune** [NikeZero1412/Optical-Character-recognition-from-images-using-CRF#1]
I have read your code in OCR-CRF.ipynb. It's cool to implement yourself in Python. But I have some confusions. 

It seems that the function "node_potentials" calculates the potential following the equation correctly. But why you use the function "feature_potentials" later instead of node_potentials for calculating psi, belief, grad, etc. But "feature_potentials" neglects the label yi ?

Could you give me some advice or explanations about that ? Thanks.

**Comment by snknitin** [comment]
Both of them are essentially the same and don't need the label yi,  except that feature_potential function is the log of node potentials.  Node potential function was just to tabulate exponential(and positive) values for the 'etainoshrd' array

**Comment by dominjune** [comment]
Sorry I am still confused. So where the indication function [yij = c] has been used in ?
